version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      # Install bundler
      - run:
      name: Install bundler
      command: sudo gem install bundler

      - run: mkdir $FL_OUTPUT_DIR
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - run:
          command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml
          when: always
      - store_artifacts:
          path: /Users/distiller/project/output
      - store_test_results:
          path: /Users/distiller/project/output/scan